import { readFileSync } from "node:fs";
import path from "node:path";

import type {
  IsitCodeValidation,
  IsitDimension,
  IsitIndexEntry,
  IsitIndexFile,
  IsitNode,
  IsitRouterEventType,
  IsitRouterFile,
  IsitRouterParentLevel,
} from "./types";

/**
 * The ISIT taxonomy is read from versioned JSON files in `data/isit/<version>/` (generated by
 * `data/isit/build_isit_json.py`), not from MongoDB. Every stored classification records the
 * version it was made against, so older results stay interpretable after an upgrade.
 *
 * Server-side only: the index file is ~1.3 MB. Never import this from a Client Component.
 */
export const DEFAULT_ISIT_VERSION = "0.3.12";

const CODE_PATTERN = /^\d{8,9}$/;
const VERSION_PATTERN = /^\d+\.\d+\.\d+$/;

export interface ValidateCodeOptions {
  /** Reject the code unless it belongs to this dimension. */
  dimension?: IsitDimension;
  /** Reject the code unless it sits under (or is) one of these nodes, e.g. the routed level-2 branches. */
  withinBranches?: readonly string[];
}

export interface IsitTaxonomy {
  version: string;
  /** Level-1 groups with their level-2 event types, for the routing stage. */
  router: IsitRouterParentLevel[];
  /** Assignable codes only. */
  entries: IsitIndexEntry[];
  getNode(code: string): IsitNode | undefined;
  getEntry(code: string): IsitIndexEntry | undefined;
  /** Nearest-first chain up to (and including) the level-1 group. */
  ancestors(code: string): IsitNode[];
  isDescendantOf(code: string, ancestorCode: string): boolean;
  /** Assignable codes under a branch, the branch itself included when it is assignable. */
  subtree(branchCode: string): IsitIndexEntry[];
  validateCode(code: string, options?: ValidateCodeOptions): IsitCodeValidation;
  /** Drops duplicates and any code whose descendant is also present (keeps the most specific). */
  collapseRedundant(codes: readonly string[]): string[];
}

const cache = new Map<string, IsitTaxonomy>();

function readJson<T>(version: string, file: string): T {
  const fullPath = path.join(process.cwd(), "data", "isit", version, file);
  return JSON.parse(readFileSync(fullPath, "utf8")) as T;
}

function l2Node(parent: IsitRouterParentLevel, eventType: IsitRouterEventType, selectable: boolean): IsitNode {
  return {
    code: eventType.code,
    level: 2,
    name: eventType.name,
    label: `${parent.name} > ${eventType.name}`,
    dimension: eventType.dimension,
    parentCode: parent.code,
    selectable,
    synthesized: !selectable,
  };
}

function build(version: string): IsitTaxonomy {
  const index = readJson<IsitIndexFile>(version, "isit-index.json");
  const routerFile = readJson<IsitRouterFile>(version, "isit-router.json");

  for (const [file, fileVersion] of [
    ["isit-index.json", index.meta.version],
    ["isit-router.json", routerFile.meta.version],
  ]) {
    if (fileVersion !== version) {
      throw new Error(`ISIT ${file} in data/isit/${version}/ declares version ${fileVersion}`);
    }
  }

  const nodes = new Map<string, IsitNode>();
  const branchDimension = new Map<string, IsitDimension>();

  for (const parent of routerFile.parentLevels) {
    for (const eventType of parent.eventTypes) branchDimension.set(eventType.code, eventType.dimension);
  }

  // A code's dimension is its level-2 branch's dimension. The generated 0.3.12 files label 97
  // descendants of the contributing branches Fatigue, Stress and Coordination/Communications as
  // "context" (build-script bug, fixed there), so the router's branch value is treated as the truth.
  const rawByCode = new Map(index.entries.map((entry) => [entry.code, entry]));
  function branchOf(entry: IsitIndexEntry): string {
    if (entry.level === 2) return entry.code;
    // Level-3 parents are level-2 branches (possibly synthesized, so not in the index).
    if (entry.level === 3) return entry.parentCode;
    return rawByCode.get(entry.parentCode)?.parentCode ?? entry.parentCode;
  }
  const entries = index.entries.map((entry) => {
    const dimension = branchDimension.get(branchOf(entry));
    if (!dimension) {
      throw new Error(`ISIT ${version}: ${entry.code} has no level-2 branch in the router`);
    }
    return dimension === entry.dimension ? entry : { ...entry, dimension };
  });
  const entryByCode = new Map(entries.map((entry) => [entry.code, entry]));

  for (const parent of routerFile.parentLevels) {
    nodes.set(parent.code, {
      code: parent.code,
      level: 1,
      name: parent.name,
      label: parent.name,
      dimension: parent.dimension,
      parentCode: null,
      selectable: false,
      synthesized: false,
    });
    for (const eventType of parent.eventTypes) {
      nodes.set(eventType.code, l2Node(parent, eventType, entryByCode.has(eventType.code)));
    }
  }

  for (const entry of entries) {
    if (entry.level === 2) continue; // already added from the router
    nodes.set(entry.code, {
      code: entry.code,
      level: entry.level,
      name: entry.name,
      label: entry.label,
      dimension: entry.dimension,
      parentCode: entry.parentCode,
      selectable: true,
      synthesized: false,
    });
  }

  const children = new Map<string, string[]>();
  for (const node of nodes.values()) {
    if (node.parentCode === null) continue;
    if (!nodes.has(node.parentCode)) {
      throw new Error(`ISIT ${version}: ${node.code} points to missing parent ${node.parentCode}`);
    }
    const siblings = children.get(node.parentCode) ?? [];
    siblings.push(node.code);
    children.set(node.parentCode, siblings);
  }

  // Parents come from the explicit `parentCode` link, never from string prefixes:
  // "1001" (from 10010000, ATC Service Standard) is also a prefix of 100010000 (Security).
  function ancestors(code: string): IsitNode[] {
    const chain: IsitNode[] = [];
    let parentCode = nodes.get(code)?.parentCode ?? null;
    while (parentCode !== null) {
      const parent = nodes.get(parentCode);
      if (!parent) break;
      chain.push(parent);
      parentCode = parent.parentCode;
    }
    return chain;
  }

  function isDescendantOf(code: string, ancestorCode: string): boolean {
    return ancestors(code).some((node) => node.code === ancestorCode);
  }

  function subtree(branchCode: string): IsitIndexEntry[] {
    const result: IsitIndexEntry[] = [];
    const stack = nodes.has(branchCode) ? [branchCode] : [];
    while (stack.length) {
      const code = stack.pop()!;
      const entry = entryByCode.get(code);
      if (entry) result.push(entry);
      stack.push(...(children.get(code) ?? []));
    }
    return result.sort((a, b) => a.label.localeCompare(b.label));
  }

  function validateCode(code: string, options: ValidateCodeOptions = {}): IsitCodeValidation {
    const reject = (reason: Extract<IsitCodeValidation, { ok: false }>["reason"], message: string) =>
      ({ ok: false, code, reason, message }) as const;

    if (!CODE_PATTERN.test(code)) {
      return reject("malformed", `"${code}" is not an 8-9 digit ISIT code`);
    }
    const node = nodes.get(code);
    if (!node) {
      return reject("unknown_code", `${code} does not exist in ISIT ${version}`);
    }
    const entry = entryByCode.get(code);
    if (!entry) {
      const why = node.level === 1 ? "is a level-1 group header" : "is a synthesized branch with no official row";
      return reject("not_selectable", `${code} (${node.label}) ${why}`);
    }
    if (options.dimension && entry.dimension !== options.dimension) {
      return reject(
        "dimension_mismatch",
        `${code} (${entry.label}) is a ${entry.dimension} code, expected ${options.dimension}`
      );
    }
    if (
      options.withinBranches &&
      !options.withinBranches.some((branch) => branch === code || isDescendantOf(code, branch))
    ) {
      return reject("outside_branch", `${code} (${entry.label}) is not under ${options.withinBranches.join(", ")}`);
    }
    return { ok: true, entry };
  }

  function collapseRedundant(codes: readonly string[]): string[] {
    const unique = [...new Set(codes)];
    return unique.filter((code) => !unique.some((other) => other !== code && isDescendantOf(other, code)));
  }

  return {
    version,
    router: routerFile.parentLevels,
    entries,
    getNode: (code) => nodes.get(code),
    getEntry: (code) => entryByCode.get(code),
    ancestors,
    isDescendantOf,
    subtree,
    validateCode,
    collapseRedundant,
  };
}

export function loadIsitTaxonomy(version: string = DEFAULT_ISIT_VERSION): IsitTaxonomy {
  if (!VERSION_PATTERN.test(version)) {
    throw new Error(`Invalid ISIT version "${version}"`);
  }
  let taxonomy = cache.get(version);
  if (!taxonomy) {
    taxonomy = build(version);
    cache.set(version, taxonomy);
  }
  return taxonomy;
}
